<div style="border-top: 1px solid #000000; text-align: center; padding-top: 3mm; font-size: 8px;">Page <?php echo $page;?> of <?php echo $topage;?></div>
<p style="text-align:center; font-size: 8px;">
	CONFIDENTIALITY NOTICE: The information contained in this document or facsimile transmission is intended for the recipient named above. If you are not the intended recipient or the intended recipient's agent, you are hereby notified that dissemination, copying, or distribution of the information contained in the transmission is prohibited. If you are not the intended recipient, please notify us immediately by telephone and return the documents to us by mail. Thank you.
</p>
<p style="text-align:center; font-size: 8px;">
	This document was generated by NOSH ChartingSystem
</p>
